version: '3.8'
services:
  api-tests-dev:
    build: .
    image: api-tests
    container_name: api-test-dev
    volumes:
      - $PWD/new-reports/dev:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run greetings greetings_dev
  api-tests-stg:
    build: .
    image: api-tests
    container_name: api-test-stg
    volumes:
      - $PWD/new-reports/stg:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run greetings greetings_stg
  api-tests-prd:
    build: .
    image: api-tests
    container_name: api-test-prod
    volumes:
      - $PWD/new-reports/prd:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run greetings greetings_prod
